version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: phish
      POSTGRES_USER: phish
      POSTGRES_PASSWORD: phish
    ports: ["5433:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  app:
    build: .
    depends_on: [postgres, redis]
    ports: ["8080:8080"]
    env_file:
      - .env
